### ISSUE TITLE
ERROR: Failed building wheel for leidenalg in Colab Environment

### ISSUE THREAD

**Issue by cmboye** [vtraag/leidenalg#105] opened 2022-05-09 15:42 UTC
Hello, 

I am trying to install leidenalg to ultimately run BPNet. I am using a Google Colab environment with Python 3.6. Please see below:

```
!sudo apt-get install build-essential autoconf automake flex bison
!sudo update-alternatives --config python3
!sudo apt install python3-pip
!python -m pip install --upgrade pip
!apt-get install -y bedtools > /dev/null
!pip install pprint -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com
!pip install git+https://github.com/kundajelab/DeepExplain.git --quiet
!pip install -U cloudpickle<1.7.0 h5py tqdm --quiet
!pip install -U pyyaml --quiet
!pip install igraph
!pip install leidenalg --no-use-pep517
!export DISABLE_BCOLZ_AVX2=true
!pip install bpnet --quiet --quiet
```

I get the following error:  `ERROR: Failed building wheel for leidenalg`. Do you know what might cause this? I do not think I will be able to use a different version of Python due to errors with other dependencies. Thank you!

**Comment by vtraag** [comment] 2022-07-13 10:04
When I try to run this on Google Colab, I don't get an error at `leidenalg` installation (although it does install version 0.8.9 instead of 0.8.10, not sure what is the problem there). However, it does error out at the installation of `bpnet` giving:

```
ERROR: Cannot install bpnet because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

So, I don't know exactly what the problem is, but it doesn't seem there is a problem with `leidenalg`, but with `bpnet`.

**Comment by vtraag** [comment] 2022-09-30 09:40
I'm closing this issue for now. Feel free to re-open if necessary.

**Closed by vtraag** 2022-09-30 09:40 UTC
