### ISSUE TITLE
0.8.0 much slower than 0.7.0?

### ISSUE THREAD

**Issue by ShobiStassen** [vtraag/leidenalg#35] opened 2020-06-02 05:12 UTC
hello,
I noticed that when I updated to the latest leidenalg (0.8.0) the runtime of calling find_parition() on a graph of around 1M nodes took over an hour compared to the usual 5-10 minutes. 

I uninstalled v0.8.0 and reinstalled 0.7.0 (pip install leidenalg == 0.7.0) and found that the runtime when calling find_partition() went back to the fast 5-10 minutes. I'm using python 3.7. 
This is how I call the function: 
`partition = leidenalg.find_partition(G_sim, leidenalg.ModularityVertexPartition,n_iterations =n_iter_leiden,seed=partition_seed)`

Is there some parameter I am overlooking that needs to be set when using find_partition() in 0.8.0 ? The function (called from 0.8.0) runs to completion on smaller graphs where the runtime difference is less noticeable. 
Thank you

**Comment by vtraag** [comment] 2020-06-02 05:21
That is quite disconcerting! What OS are you on? Does it only have this problem on a particular network? I will run some further tests on my side.

**Comment by vtraag** [comment] 2020-06-02 05:31
@iosonofabio, could you perhaps also take a look? The part that is most likely affecting the runtime is the idea of keeping some nodes "fixed". Did you check the impact on the runtime? If the impact is too great, I might need to take it out again. Perhaps some part can be improved still, perhaps you can take a closer look?

**Comment by ShobiStassen** [comment] 2020-06-02 05:35
Hi again,

I ran 0.8.0 on 3 different datasets (1.3 Million Mouse Neuron from 10X, first 20 PCs, [1.1M lung cancer cells with 24 features](https://data.mendeley.com/datasets/nnbfwjvmvw/draft?a=dae895d4-25cd-4bdf-b3e4-57dd31c11e37) and some other single-cell large datasets).
The input to leidenalg is a KNN-Graph of the original data.
I'm running on Ubuntu 16.04, Intel® Xeon(R) W-2123 CPU @ 3.60GHz × 8 , 126 GB Ram.

**Comment by ShobiStassen** [comment] 2020-06-02 05:36
@vtraag  I should also take this opportunity to thank you for a wonderful algorithm!

**Comment by iosonofabio** [comment] 2020-06-02 05:38
I'll have a look. I need that though so if it goes out I'll fork the repo.

**Comment by vtraag** [comment] 2020-06-02 05:48
Thanks @ShobiStassen! @iosonofabio, I'd be happy to keep the feature in. But if it has such a large effect on the runtime, it will be causing too much downsides to keep it in in its current form. We can talk about the details of changing the implementation after we have taken a closer look. Perhaps we come to the conclusion that it is better to have your own fork (sort of `northstar-leiden`), but perhaps we find a way to keep it in, without the large runtime effects.

**Comment by iosonofabio** [comment] 2020-06-02 05:54
@vtraag my thoughts exactly

**Comment by iosonofabio** [comment] 2020-06-02 07:44
Also, @ShobiStassen: is Leiden the bottleneck in runtime in your analysis? In my experience:

1. even though Leiden might be a little slower, it is by far not the bottleneck
2. Most datasets are much smaller than 1.1M cells. In fact, collecting that amount of data costs around $400k, so it's something only dedicated labs will do.

That said, of course we should try to be as efficient as possible.

**Comment by ShobiStassen** [comment] 2020-06-02 08:05
@iosonofabio hi, the runtime for the knngraph for these datasets takes around 5 mins, so when using v0.8.0 of Leiden, the Leiden step is the bottleneck

**Comment by ShobiStassen** [comment] 2020-06-02 08:06
I've also run this on some older cytometry datasets of around 300,000 cells and the v0.7.0 takes around two mins whereas I terminated the Leiden after around 15mins for v0.8.0

**Comment by vtraag** [comment] 2020-06-02 08:08
Perhaps we should just use a common benchmark to check the speed of `leidenalg` (and only `leidenalg`). Perhaps we can use the dataset linked by @ShobiStassen. Perhaps you can provide some code as to how to create the exact graph you are running `leidenalg` on, @ShobiStassen?

**Comment by iosonofabio** [comment] 2020-06-02 08:12
@vtraag That's a great idea, it will help us debug. Also a smaller version that takes only 10 seconds would help

@ShobiStassen usually there is a lot of preprocessing for things like dimensionality reduction, feature selection, normalization etc etc. that's where the time usually goes. But that's out of the scope of this issue: we should just try and see what the problem is

**Comment by ShobiStassen** [comment] 2020-06-02 08:16
Hi for sure, let me share that with you by your tomorrow morning (I'm in
Singapore atm)

**Comment by iosonofabio** [comment] 2020-06-02 08:19
Awesome thanks! Btw you making the graph using this method?

https://ieeexplore.ieee.org/document/8594636

That might be more scalable than naive O(N^2) approaches, which would explain why Leiden becomes the bottleneck. Another way of approximating that graph that scales to 100 million cells - or high-dimensional data point - is [lshknn](https://github.com/iosonofabio/lshknn) which is based on Paolo Carnevali @CZI (https://github.com/chanzuckerberg/ExpressionMatrix2)

**Comment by ShobiStassen** [comment] 2020-06-02 08:20
Agree that other preprocessing can take a lot of time but in this instance
the times I have mentioned are after preprocessing and after graph
construction and only timed once the find_partition() is started.

**Comment by ShobiStassen** [comment] 2020-06-02 08:24
@iosonofabio cool ! I will check out the graph approx methods , I use hnsw to make the knngraph  and then do some pruning before inputting to Leidenalg(on my GitHub repo for PARC clustering on large scale single cell data).

**Comment by iosonofabio** [comment] 2020-06-03 04:56
Alright, I took a knn graph from a typical single cell dataset (kidney droplet data from Tabula Muris Senis, https://www.biorxiv.org/content/10.1101/661728v1). The graph has 11,666 vertices and 93,030 edges (unweighted, undirected). As a fun side note, I was the person preparing the experimental sample as well ^^

I tested two versions of leidenalg:
- the commit before my fixed node branch was merged first (notice there were two merges) (defe55a8ab221541c5b9ba80788c5d9796c0f32c)
- the commit after my fixed node branch was merged last (1aa7efc335fddd280ddd1cba5b7a3deb6974170f)

Both were linked against current igraph 0.8.2.

Results here below for 30 simulations of each version:
![leidenalg_profiling](https://user-images.githubusercontent.com/1200640/83596728-bc45c800-a5a8-11ea-97ef-42548ce75136.png)

The machinery of fixed nodes slows it down by 5% on average. As a comparison, the stochastic nature of Leiden causes a 3% standard deviation on runtime.

This indicates that the fixed nodes do not have a strong impact on performance, which was already my impression back then when I was developing this.

Here the edge list (tab separated, each line an edge) for your own tests:

[example_edges.txt](https://github.com/vtraag/leidenalg/files/4721100/example_edges.txt)

What's the conclusion? I think it's possible that one of the following happened:
1. igraph 0.7 -> 0.8 caused the slowdown (if so, we should find it and fix it)
2. another commit on leidenalg caused the slowdown (if so, which one?)
3. it only manifests on extremely large graphs (if so, why? 100k edges is already pretty large)
4. typos on the user side, e.g. comparing two slightly different workflows

@ShobiStassen could you try how long it takes to cluster the graph attached with CPM? This is on my low-voltage CPU laptop so it should be around that time or faster. This is how I do the timing:

![image](https://user-images.githubusercontent.com/1200640/83597310-5bb78a80-a5aa-11ea-84c2-8259ab2707ec.png)

**Comment by ShobiStassen** [comment] 2020-06-03 07:45
Hi again,
I ran your code for the kidney graph as well as a larger graph
[70K_LC_edgelist.txt](https://github.com/vtraag/leidenalg/files/4721710/70K_LC_edgelist.txt)
of Lung Cancer cells and get the following runtimes. I only ran each dataset 10 times for each version of Leidenalg (080, and 070). I used the same conda environment but just pip uninstalled and reinstalled the required version of Leidenalg leaving everything else the same (the version of python igraph in this environment is `0.8.2).`
The larger graph has 70,000 nodes and 2.1Million edges. As you can see from the output, the runtime is about 2x for the newer leidenalg on this graph. 


![image](https://user-images.githubusercontent.com/35950152/83608950-24e47300-a5b0-11ea-9e93-7386cfca7d06.png)

Here is how i read the file:
` kidney_g = ig.Graph.Read_Ncol('/home/shobi/Downloads/example_edges.txt', directed=False)`

I use the same function calls as you:
`

        partition = leidenalg.CPMVertexPartition(kidney_g, resolution_parameter=0.01)
        opt = leidenalg.Optimiser()
        opt.optimise_partition(partition)

        #partition = leidenalg.find_partition(kidney_g,leidenalg.ModularityVertexPartition)
        t1 = time.time()
        dt = t1-t0`

**Comment by iosonofabio** [comment] 2020-06-03 08:27
Thanks for that. It's interesting because:

1. The larger graph seems to suffer more
2. Even the smaller graph has a 60% runtime increase for you, but only a 5% increase for me
3. Your runtimes are generally slower than mine, which is unexpected because I'm on a slow laptop CPU.

@vtraag any ideas? Notice that the comparison is a little tricky because @ShobiStassen compared 0.7.0 versus 0.8.0, whereas I surgically extracted the exact commits around the fixed nodes, which is a slightly different thing.

**Comment by iosonofabio** [comment] 2020-06-03 08:43
I added the commits tagged `0.7.0` and `0.8.0` to the benchmark:

![leidenalg_profiling2](https://user-images.githubusercontent.com/1200640/83615286-b0b6c900-a5c9-11ea-8e16-366cd646cd42.png)

Clearly something happened between the fixed node second (and final) merge and the released 0.8.0.

@vtraag since you are more familiar with the repo, would you mind doing a little bit of bisectioning? Otherwise I can do it too if you tell me the hashes of commits you would like to test.

As a side note, recent versions don't compile here because line 498 of the `setup.py` uses `detected` before it's ever defined. I set it to false since the header path and solib name were already correct for Arch Linux.

**Comment by vtraag** [comment] 2020-06-03 08:56
Thanks for looking into this, both of you. I will try to see what other things could be causing this. 

Possibly, it may be an issue with optimization flags, I'm not sure. @iosonofabio, are you compiling each version yourself, or not?

 > recent versions don't compile here because line 498 of the setup.py uses detected before it's ever defined.

That is something that should then also affect `python-igraph`. Could you open an [issue](https://github.com/igraph/python-igraph/issues/) for that so that we don't loose track?

> I set it to false since the header path and solib name were already correct for Arch Linux.

I'm not sure I understand: you mean you are compiling & linking against an external version of `igraph` instead of the vendored source?

**Comment by iosonofabio** [comment] 2020-06-03 09:06
I **think** that I'm compiling against the external shared library of igraph, since a typical call during the `python setup.py build` is:

```bash
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fno-semantic-interposition -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -Iinclude -I/usr/include/igraph -I/usr/local/include/igraph -I/usr/include/python3.8 -c src/python_optimiser_interface.cpp -o build/temp.linux-x86_64-3.8/src/python_optimiser_interface.o
```
(notice the `-I/usr/include/igraph`).

Yes I'm compiling everything (except igraph I think). I do this:
```bash
git checkout <commit hash>
python setup.py build
mv build/lib.linux-x86_64-3.8/leidenalg build/lib.linux-x86_64-3.8/leidenalg_before
```
and similar for the other ones. Then in the script:
```python
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__))+'/build/lib.linux-x86_64-3.8')
import leidenalg_before
import leidenalg_after
import leidenalg_070
import leidenalg_080
modules = {
        'before': leidenalg_before,
        'after': leidenalg_after,
        '0.7.0': leidenalg_070,
        '0.8.0': leidenalg_080,
        }
```

so I can test them all in the same go.

**Comment by vtraag** [comment] 2020-06-03 09:30
OK, thanks for sharing your setup @iosonofabio. In fact, there were a couple of additional commits necessary to make everything run correctly beyond commit https://github.com/vtraag/leidenalg/commit/1aa7efc335fddd280ddd1cba5b7a3deb6974170f that you tested. I think the implementation of the fixed nodes should be complete after commit
https://github.com/vtraag/leidenalg/commit/248cce7bb75882c2b0f292f4780d0e77bb5e0b5c. Could you perhaps test that?

**Comment by iosonofabio** [comment] 2020-06-03 09:37
![leidenalg_profiling3](https://user-images.githubusercontent.com/1200640/83621081-8f59db00-a5d1-11ea-8d6c-8390b5484cb2.png)
Couldn't be more excruciating ;-)

**Comment by vtraag** [comment] 2020-06-03 09:50
OK, thanks for checking! I have an idea what might be causing the slowdown, I'm checking it now.

**Comment by ntamas** [comment] 2020-06-03 10:26
Just wanted to chime in to say I'm following things - this is better than investigative journalism :) Keep up the good work!

**Comment by vtraag** [comment] 2020-06-03 11:34
@iosonofabio, @ShobiStassen , I think I found the problem. For some reason I thought something was wrong previously (when in fact it was not), which I believe to be responsible for the large difference in runtimes. Could you please check the solution in PR #36? It will not be exactly on par with the version 0.7.0, because there were actually some things that did need to be corrected, but it should be more in line with only a few % slower runtimes.

**Comment by ragibson** [comment] 2020-06-13 18:22
I ran into this while testing another issue.

For what it's worth, I found that 75% (!) of the optimization time on a 100 layer temporal network was coming from a single C++ iterator in MutableVertexPartition::cache_neigh_communities, so https://github.com/vtraag/leidenalg/pull/36 is definitely on the right track.

In particular, I suspect the statement below causes the vast majority of the performance regression you're seeing.
https://github.com/vtraag/leidenalg/blob/f24f0be2bb8754f551a1054e9f93bc2721df16fb/src/MutableVertexPartition.cpp#L766-L767

**Comment by ragibson** [comment] 2020-06-13 18:36
Yes, the fix in https://github.com/vtraag/leidenalg/pull/36 is more than twice as fast as the code in the master branch for this multilayer network.

**Comment by vtraag** [comment] 2020-06-13 19:37
Thanks @ragibson ! Could you also confirm the improvement @iosonofabio and @ShobiStassen ? I will then merge and release a new version.

**Comment by iosonofabio** [comment] 2020-06-13 22:48
yep

![leidenalg_profiling4](https://user-images.githubusercontent.com/1200640/84580611-c7f08480-ae1b-11ea-81c4-43c23543fb4a.png)
![leidenalg_profiling4_density](https://user-images.githubusercontent.com/1200640/84580613-c921b180-ae1b-11ea-8b08-f2d15308269f.png)

**Closed** 2020-06-23 06:17 UTC
